{% set name = "pyftpdlib" %}
{% set version = "1.5.6" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: fda655d81f29af52885ca2f8a2704134baed540f16d66a0b26e8fdfafd12db5e

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vvv"

requirements:
  host:
    - pip
    - python
  run:
    - python

test:
  imports:
    - pyftpdlib

about:
  home: "https://github.com/giampaolo/pyftpdlib/"
  license: MIT
  license_family: MIT
  license_file:
  summary: "Very fast asynchronous FTP server library"
  doc_url:
  dev_url:

extra:
  recipe-maintainers:
    - your-github-id-here
